version: "3.8"

services:
  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./db/:/db/

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/db/